import Head from 'next/head';
import { Inter } from 'next/font/google';
import { Button, Text } from '@components/atoms';
import { Field } from '@components/molecules';
import styles from '@styles/pages/Home.module.scss';
import SubscribeNewsletter from '@components/organisms/form/SubscribeNewsLetter/SubscribeNewsletter';
import { useState } from 'react';
import { AbstractDiagram, AbstractScore } from '@assets/svg/abstract';
import Abstract from '@components/pages/Abstract/Abstract';
import { IconCheck } from '@assets/svg/icons';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [subscribed, setSubscribed] = useState(false);
  const [subscribedEmail, setSubscribedEmail] = useState<string | null>(null);

  const handleSuccessfulSubmit = (email: string) => {
    setSubscribed(true);
    setSubscribedEmail(email);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='rootContainer'>
        {subscribed ? (
          <div>
            yes {subscribedEmail}
            <button
              onClick={() => {
                setSubscribed(false);
              }}
            >
              close
            </button>
          </div>
        ) : (
          <section className={styles.content}>
            <div className={styles.content_form}>
              <div className={styles.content_info}>
                <Text tag='h1' className='text_xl'>
                  Stay uptated !
                </Text>
                <Text tag='p'>
                  Join 60,000+ product managers receiving monthly updates on:
                </Text>

                <ul>
                  <li>
                    <IconCheck /> discovery and building what matters
                  </li>
                  <li>
                    <IconCheck />
                    Measuring to ensure updates are a success
                  </li>
                  <li>
                    <IconCheck />
                    And much more!
                  </li>
                </ul>
              </div>
              <SubscribeNewsletter
                onSuccessfulSubmit={handleSuccessfulSubmit}
              />
            </div>
            <Abstract />
          </section>
        )}
      </main>
    </>
  );
}
